language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.5.2
# command to install dependencies
install:
  - "pip install ."
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
# command to run tests
script: nosetests
